//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeWPF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cafe_dbEntities : DbContext
    {
        public cafe_dbEntities()
            : base("name=cafe_dbEntities")
        {
        }
        private static cafe_dbEntities _context;
        public static cafe_dbEntities GetContext()
        {
            if (_context == null)
                _context = new cafe_dbEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DishTable> DishTables { get; set; }
        public virtual DbSet<DrinkTable> DrinkTables { get; set; }
        public virtual DbSet<GenderTable> GenderTables { get; set; }
        public virtual DbSet<PositionTable> PositionTables { get; set; }
        public virtual DbSet<SmenaTable> SmenaTables { get; set; }
        public virtual DbSet<StatusCookTable> StatusCookTables { get; set; }
        public virtual DbSet<StatusOficTable> StatusOficTables { get; set; }
        public virtual DbSet<StatusWorkerTable> StatusWorkerTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<WorkTable> WorkTables { get; set; }
        public virtual DbSet<ZakazTable> ZakazTables { get; set; }
    }
}
