//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmenaTable
    {
        public int IDSmena { get; set; }
        public Nullable<int> Worker { get; set; }
        public Nullable<System.DateTime> DateExit { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
    
        public virtual WorkTable WorkTable { get; set; }
    }
}
