//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkTable()
        {
            this.SmenaTables = new HashSet<SmenaTable>();
            this.ZakazTables = new HashSet<ZakazTable>();
        }
    
        public int IDWorker { get; set; }
        public string Fname { get; set; }
        public string Name { get; set; }
        public string Lname { get; set; }
        public Nullable<System.DateTime> DateBirthday { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> WorkPosition { get; set; }
        public Nullable<int> Status { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual GenderTable GenderTable { get; set; }
        public virtual PositionTable PositionTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SmenaTable> SmenaTables { get; set; }
        public virtual StatusWorkerTable StatusWorkerTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZakazTable> ZakazTables { get; set; }
    }
}
