//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZakazTable
    {
        public int IDZakaz { get; set; }
        public Nullable<int> StatusOfic { get; set; }
        public Nullable<int> StatusCook { get; set; }
        public Nullable<int> Oficiant { get; set; }
        public Nullable<int> NTable { get; set; }
        public Nullable<int> NDish { get; set; }
        public Nullable<int> NDrink { get; set; }
        public Nullable<System.DateTime> DateZakaz { get; set; }
    
        public virtual DishTable DishTable { get; set; }
        public virtual DrinkTable DrinkTable { get; set; }
        public virtual StatusCookTable StatusCookTable { get; set; }
        public virtual StatusOficTable StatusOficTable { get; set; }
        public virtual WorkTable WorkTable { get; set; }
    }
}
